### ISSUE TITLE
Debugger won't Pause/Step and TypeError [ERR_INVALID_ARG_TYPE]: ver 0.9.13

### ISSUE THREAD

**Issue by JosephChackungal** [APerricone/harbourCodeExtension#67]
Hi,
I have recently downloaded your fantastic extension for VS Code. All works fine and many thanks for this great work! Changed the world for me!
The only issue is I am not able to get the debugger to work as required.
I have downloaded the debug source prg and added to my project and the project is compiled with -b.
When I launch the project for debugging - it launches the target application and I get the Navigation Bar with:
1. Pause - enabled, but won't pause.
2. All 3 Step icons are disabled.
3. Restart and Stop are enabled and works but gives the error - "TypeError [ERR_INVALID_ARG_TYPE]: The "pid" argument must be of type number. Received type undefined
    at process.kill (internal/process/per_thread.js:171:13)
    at harbourDebugSession.terminateRequest (c:\Users\JC\.vscode\extensions\aperricone.harbour-0.9.13\dist\debugger.js:1:28190)
    at harbourDebugSession.dispatchRequest (c:\Users\JC\.vscode\extensions\aperricone.harbour-0.9.13\dist\debugger.js:1:12274)
    at harbourDebugSession.handleMessage (c:\Users\JC\.vscode\extensions\aperricone.harbour-0.9.13\dist\debugger.js:1:38633)
    at harbourDebugSession._handleData (c:\Users\JC\.vscode\extensions\aperricone.harbour-0.9.13\dist\debugger.js:1:40458)
    at Socket.<anonymous> (c:\Users\JC\.vscode\extensions\aperricone.harbour-0.9.13\dist\debugger.js:1:38965)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)."

Tried looking for help online, tried simple programs - same result!
What am I doing wrong here?
OS: Win 10 64, HB32.
Thanks,

**Comment by JosephChackungal** [comment]
Problem Solved! My silly mistake!!
I was using two different project files and both had '-l' in it! so the compiled object files were without line number information!
The debugger works like a gem!
Thanks

**Comment by APerricone** [comment]
sorry, I saw this only now
