### ISSUE TITLE
Error on starting 0.9.15

### ISSUE THREAD

**Issue by mlacecilia** [APerricone/harbourCodeExtension#69]
ReferenceError: pbd is not defined
    at l.findDBReferences (c:\Users\Maurizio\.vscode\extensions\aperricone.harbour-0.9.15\server\dist\hb_server.js:1:77544)
    at l.parse (c:\Users\Maurizio\.vscode\extensions\aperricone.harbour-0.9.15\server\dist\hb_server.js:1:75081)
    at Interface.<anonymous> (c:\Users\Maurizio\.vscode\extensions\aperricone.harbour-0.9.15\server\dist\hb_server.js:1:76754)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at ReadStream.ondata (readline.js:186:10)
    at ReadStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:267:11)
[Error - 19:13:51] Connection to server got closed. Server will not be restarted.

**Comment by APerricone** [comment]
ole '! I skipped the usual testing period and here is the result, I will solve as soon as possible. thanks for the issue report
