### ISSUE TITLE
Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by angelvisionwin** [APerricone/harbourCodeExtension#71]
Hello!, copy/paste part of log error after updating to version 1.0.0

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, open 'C:\SI\NLEN\FWH1906\INCLUDE\Video.ch'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:136:12
    at FSReqCallback.oncomplete (fs.js:160:23) {
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\SI\\NLEN\\FWH1906\\INCLUDE\\Video.ch'
}
[Info  - 10:46:20] Connection to server got closed. Server will restart.
```

**Comment by APerricone** [comment]
Very interesting, I just saw that the server open the includes a lot of times and I fixed it, but it is not a strong solution for this crash, it needs to keep track of the number of opened files, It will take a while
